-define(DOCROOT,"priv/www").
-define(DEFAULT_PORT,8080).
-record(state,{user_list=[],last_msg_queue}).
-record(user,{username,pid,channel,ref,in_time,host=false,room_name}).
-define(MAX_USER,100).%% user number limit.
-define(MAX_ROOM_NUM,100).
-define(MAX_CONNECTION_ONE_ROOM,50).
-define(MAX_LAST_MSG_LEN,50). %%keep lastest message in history box
-define(WELCOME_MSG,"").
-define(ADMIN_NAME,"admin.tom").
-record(msg,{type,time,username,value}).